/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/n4s8OgnIUqd
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/
import { Button } from "@/components/ui/button"
import { CardTitle, CardDescription, CardHeader, Card, CardContent, CardFooter } from "@/components/ui/card"
import { Input } from "@/components/ui/input"
import { Textarea } from "@/components/ui/textarea"

export function ProjectLanding() {
  return (
    <div className="min-h-screen bg-gray-100 flex flex-col items-center">
      <header className="w-full bg-white shadow-md">
        <div className="container mx-auto py-4 px-6 flex justify-between items-center">
          <h1 className="text-2xl font-bold text-gray-800">Creative Writing App</h1>
          <nav className="space-x-4">
            <a href="#" className="text-gray-600 hover:text-gray-800">
              Features
            </a>
            <a href="#" className="text-gray-600 hover:text-gray-800">
              About
            </a>
            <a href="#" className="text-gray-600 hover:text-gray-800">
              Contact
            </a>
          </nav>
        </div>
      </header>
      <main className="flex-1 container mx-auto py-12 px-6">
        <section className="text-center mb-12">
          <h2 className="text-4xl font-bold text-gray-800 mb-4">Welcome to Your New Writing Home</h2>
          <p className="text-gray-600 mb-8">
            A novel and revolutionary platform for creative writers to express themselves.
          </p>
          <Button className="bg-primary text-white px-6 py-3 rounded-md">Get Started</Button>
        </section>
        <section id="features" className="mb-12">
          <h3 className="text-3xl font-bold text-gray-800 mb-6">Features</h3>
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
            <Card>
              <CardHeader>
                <CardTitle>Seamless Writing</CardTitle>
                <CardDescription>Write without distractions with our clean and intuitive interface.</CardDescription>
              </CardHeader>
            </Card>
            <Card>
              <CardHeader>
                <CardTitle>Collaboration</CardTitle>
                <CardDescription>Work with other writers in real-time and share your progress.</CardDescription>
              </CardHeader>
            </Card>
            <Card>
              <CardHeader>
                <CardTitle>Advanced Editing</CardTitle>
                <CardDescription>Utilize powerful editing tools to refine your work.</CardDescription>
              </CardHeader>
            </Card>
          </div>
        </section>
        <section id="about" className="mb-12">
          <h3 className="text-3xl font-bold text-gray-800 mb-6">About Us</h3>
          <p className="text-gray-600">
            We are a team of passionate writers and developers dedicated to creating the best platform for creative
            writing. Our mission is to provide a space where writers can feel at home and unleash their creativity.
          </p>
        </section>
        <section id="contact" className="mb-12">
          <h3 className="text-3xl font-bold text-gray-800 mb-6">Contact Us</h3>
          <Card>
            <CardHeader>
              <CardTitle>Get in Touch</CardTitle>
              <CardDescription>
                We'd love to hear from you. Fill out the form below and we'll get back to you as soon as possible.
              </CardDescription>
            </CardHeader>
            <CardContent>
              <div className="space-y-4">
                <div className="space-y-2">
                  <label htmlFor="name" className="block text-sm font-medium text-gray-700">
                    Name
                  </label>
                  <Input id="name" placeholder="Enter your name" />
                </div>
                <div className="space-y-2">
                  <label htmlFor="email" className="block text-sm font-medium text-gray-700">
                    Email
                  </label>
                  <Input id="email" placeholder="Enter your email" type="email" />
                </div>
                <div className="space-y-2">
                  <label htmlFor="message" className="block text-sm font-medium text-gray-700">
                    Message
                  </label>
                  <Textarea id="message" placeholder="Enter your message" className="min-h-[100px]" />
                </div>
              </div>
            </CardContent>
            <CardFooter>
              <Button className="ml-auto">Send Message</Button>
            </CardFooter>
          </Card>
        </section>
      </main>
      <footer className="w-full bg-white shadow-md py-4">
        <div className="container mx-auto text-center text-gray-600">
          &copy; 2023 Creative Writing App. All rights reserved.
        </div>
      </footer>
    </div>
  )
}
