import { LessonGroupModel } from "@/modules/course/models/course.model";

export const CategoryLessons: Record<string, LessonGroupModel[]> = {
  "1": [
    {
      id: 1,
      title: "Logic Building",
      priority: 1,
      lessonList: [
        {
          id: 1,
          groupId: 1,
          title: "Game 1",
          description: "This is a sample game 1",
          duration: 10,
          priority: 1,
        },
        {
          id: 2,
          groupId: 1,
          title: "Game 2",
          description: "This is a sample game 2",
          duration: 10,
          priority: 2,
        },
        {
          id: 3,
          groupId: 1,
          title: "Game 3",
          description: "This is a sample game 3",
          duration: 10,
          priority: 3,
        },
      ],
    },
    {
      id: 2,
      title: "Logic Building 2",
      priority: 2,
      lessonList: [
        {
          id: 4,
          groupId: 2,
          title: "Game 4",
          description: "This is a sample game 4",
          duration: 10,
          priority: 1,
        },
        {
          id: 5,
          groupId: 2,
          title: "Game 5",
          description: "This is a sample game 5",
          duration: 10,
          priority: 2,
        },
        {
          id: 6,
          groupId: 2,
          title: "Game 6",
          description: "This is a sample game 6",
          duration: 10,
          priority: 3,
        },
      ],
    },
    {
      id: 3,
      title: "Logic Building 3",
      priority: 3,
      lessonList: [
        {
          id: 7,
          groupId: 3,
          title: "Game 7",
          description: "This is a sample game 7",
          duration: 10,
          priority: 1,
        },
        {
          id: 8,
          groupId: 3,
          title: "Game 8",
          description: "This is a sample game 8",
          duration: 10,
          priority: 2,
        },
        {
          id: 9,
          groupId: 3,
          title: "Game 9",
          description: "This is a sample game 9",
          duration: 10,
          priority: 3,
        },
      ],
    },
  ],
  "2": [
    {
      id: 1,
      title: "Logic Building",
      priority: 1,
      lessonList: [
        {
          id: 1,
          groupId: 1,
          title: "Game 1",
          description: "This is a sample game 1",
          duration: 10,
          priority: 1,
        },
        {
          id: 2,
          groupId: 1,
          title: "Game 2",
          description: "This is a sample game 2",
          duration: 10,
          priority: 2,
        },
        {
          id: 3,
          groupId: 1,
          title: "Game 3",
          description: "This is a sample game 3",
          duration: 10,
          priority: 3,
        },
      ],
    },
    {
      id: 2,
      title: "Logic Building 2",
      priority: 2,
      lessonList: [
        {
          id: 4,
          groupId: 2,
          title: "Game 4",
          description: "This is a sample game 4",
          duration: 10,
          priority: 1,
        },
        {
          id: 5,
          groupId: 2,
          title: "Game 5",
          description: "This is a sample game 5",
          duration: 10,
          priority: 2,
        },
        {
          id: 6,
          groupId: 2,
          title: "Game 6",
          description: "This is a sample game 6",
          duration: 10,
          priority: 3,
        },
      ],
    },
    {
      id: 3,
      title: "Logic Building 3",
      priority: 3,
      lessonList: [
        {
          id: 7,
          groupId: 3,
          title: "Game 7",
          description: "This is a sample game 7",
          duration: 10,
          priority: 1,
        },
        {
          id: 8,
          groupId: 3,
          title: "Game 8",
          description: "This is a sample game 8",
          duration: 10,
          priority: 2,
        },
        {
          id: 9,
          groupId: 3,
          title: "Game 9",
          description: "This is a sample game 9",
          duration: 10,
          priority: 3,
        },
      ],
    },
  ],
  "3": [
    {
      id: 1,
      title: "Logic Building",
      priority: 1,
      lessonList: [
        {
          id: 1,
          groupId: 1,
          title: "Game 1",
          description: "This is a sample game 1",
          duration: 10,
          priority: 1,
        },
        {
          id: 2,
          groupId: 1,
          title: "Game 2",
          description: "This is a sample game 2",
          duration: 10,
          priority: 2,
        },
        {
          id: 3,
          groupId: 1,
          title: "Game 3",
          description: "This is a sample game 3",
          duration: 10,
          priority: 3,
        },
      ],
    },
    {
      id: 2,
      title: "Logic Building 2",
      priority: 2,
      lessonList: [
        {
          id: 4,
          groupId: 2,
          title: "Game 4",
          description: "This is a sample game 4",
          duration: 10,
          priority: 1,
        },
        {
          id: 5,
          groupId: 2,
          title: "Game 5",
          description: "This is a sample game 5",
          duration: 10,
          priority: 2,
        },
        {
          id: 6,
          groupId: 2,
          title: "Game 6",
          description: "This is a sample game 6",
          duration: 10,
          priority: 3,
        },
      ],
    },
    {
      id: 3,
      title: "Logic Building 3",
      priority: 3,
      lessonList: [
        {
          id: 7,
          groupId: 3,
          title: "Game 7",
          description: "This is a sample game 7",
          duration: 10,
          priority: 1,
        },
        {
          id: 8,
          groupId: 3,
          title: "Game 8",
          description: "This is a sample game 8",
          duration: 10,
          priority: 2,
        },
        {
          id: 9,
          groupId: 3,
          title: "Game 9",
          description: "This is a sample game 9",
          duration: 10,
          priority: 3,
        },
      ],
    },
  ],
};
